const PRODUCT_GROUP = '/products';
const CATEGORY_GROUP = '/categories';

export const INVENTORY_API_URLS = {
  CATEGORIES: `${CATEGORY_GROUP}`,
  CATEGORY_DETAIL: `${CATEGORY_GROUP}/:id`,

  PRODUCTS: `${PRODUCT_GROUP}`,
  PRODUCT_DETAIL: `${PRODUCT_GROUP}/:id`,

  PRODUCT_ATTRIBUTES: `${PRODUCT_GROUP}/attributes`,
};
